version: '3'

services:
  # # MySQL
  # mysql:
  #   container_name: mysql
  #   image: mysql:5.7
  #   platform: linux/x86_64
  #   environment:
  #     MYSQL_DATABASE: testdb
  #     MYSQL_USER: mysql
  #     MYSQL_PASSWORD: password
  #     MYSQL_ROOT_PASSWORD: password
  #     # TZ: Asia/Tokyo
  #   volumes:
  #     # データの永続化
  #     - ./data/mysql:/var/lib/mysql
  #     # 初期化スクリプトのマウント
  #     - ./conf/mysql/initdb.d:/docker-entrypoint-initdb.d
  #     # 設定ファイルのマウント
  #     - ./conf/mysql/conf.d/my.cnf:/etc/mysql/conf.d/my.cnf
  #   # restart: always

  # Postgres
  postgres:
    container_name: postgres
    image: postgres:10.21-alpine3.16
    # platform: linux/x86_64
    environment:
      # superuserの設定
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      # TZ: Asia/Tokyo
    ports:
      - 5432:5432
    volumes:
      # データの永続化
      - ./data/postgres:/var/lib/postgresql/data
      # 初期化スクリプトのマウント
      - ./conf/postgres/initdb.d:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # digdag
  digdag:
    container_name: digdag
    build:
      context: .
      dockerfile: ./conf/digdag/Dockerfile
    # platform: linux/x86_64
    ports:
      - 65432:65432
    volumes:
      # tmpとworkspaceのマウント
      - ./data/digdag/tmp:/tmp
      - ./data/digdag/workspace:/workspace
      # 設定ファイルのマウント
      - ./conf/digdag/server.properties:/etc/digdag/server.properties
    depends_on:
      # postgresのhealthcheckが成功したら起動
      postgres:
        condition: service_healthy

  # metabase
  metabase:
    container_name: metabase
    image: metabase/metabase:v0.42.3
    # platform: linux/x86_64
    environment:
      MB_DB_TYPE: postgres
      MB_DB_HOST: postgres
      MB_DB_PORT: 5432
      MB_DB_DBNAME: metabase
      MB_DB_USER: metabase
      MB_DB_PASS: password
      # JAVA_TIMEZONE=Asia/Tokyo
    ports:
      - 3000:3000
    volumes:
      # データの永続化
      - ./data/metabase:/metabase-data
    depends_on:
      # postgresのhealthcheckが成功したら起動
      postgres:
        condition: service_healthy
