CREATE TABLE IF NOT EXISTS EMPLOYEE (
  EMPLOYEE_ID VARCHAR(10) NOT NULL PRIMARY KEY,
  EMPLOYEE_NAME VARCHAR(256) NOT NULL,
  GENDER VARCHAR(256) NOT NULL,
  CREATE_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UPDATE_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

INSERT INTO EMPLOYEE (EMPLOYEE_ID, EMPLOYEE_NAME, GENDER) VALUES ('dummy', 'ダミー', 'FEMALE');
